name: Build and Push Angular Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: yourdockerhubusername/angular-app
      API_URL: http://localhost:8081/v1

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Build Docker image (with API_URL)
      - name: Build Docker image
        run: |
          docker build \
            --build-arg API_URL=${{ env.API_URL }} \
            -t ${{ env.IMAGE_NAME }}:latest .

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchaljustgrow
          password: dckr_pat_T7tgK2DZbSbLekJMq_hBE7li3nI

      # 4️⃣ Push image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
